services:
  backend:
    build:
      context: .
    container_name: ge-back
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/ge-bd
      QUARKUS_DATASOURCE_USERNAME: admin
      QUARKUS_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - ge-net

networks:
  ge-net:
    external: true
